"""Generate the Unicode tables the text frontend needs.

The self-written runtime normalises text exactly like the Hugging Face
`tokenizers` BertNormalizer that the voice package's tokenizer.json configures.
That normaliser is per-character, so the whole behaviour reduces to four
code-point classes plus one expansion table:

  control      dropped by `clean_text`
  space        rewritten to a single space by `clean_text`
  chinese      padded with spaces by `handle_chinese_chars`
  punctuation  isolated by `BertPreTokenizer`
  fold         `lowercase` followed by `strip_accents` (NFD minus Mn)

Run this script on a development machine (it needs CPython only) and commit the
generated `src/host/fsv_unicode_tables.{h,cpp}`. The runtime reads them, so it
never needs Python.

    py -3 tools/gen_unicode_tables.py
"""

from __future__ import annotations

import os
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_CPP = os.path.join(ROOT, "src", "host", "fsv_unicode_tables.cpp")
OUT_H = os.path.join(ROOT, "src", "host", "fsv_unicode_tables.h")

MAX_CP = 0x110000

# Hangul syllables decompose algorithmically; the runtime expands them in code
# so the generated table stays small.
HANGUL_SBASE = 0xAC00
HANGUL_SCOUNT = 11172

# Range constants from the Hugging Face BertNormalizer.
CHINESE_RANGES = [
    (0x4E00, 0x9FFF),
    (0x3400, 0x4DBF),
    (0x20000, 0x2A6DF),
    (0x2A700, 0x2B73F),
    (0x2B740, 0x2B81F),
    (0x2B820, 0x2CEAF),
    (0xF900, 0xFAFF),
    (0x2F800, 0x2FA1F),
]

# BertPreTokenizer isolates ASCII punctuation and every Unicode P category.
ASCII_PUNCTUATION_RANGES = [
    (0x21, 0x2F),
    (0x3A, 0x40),
    (0x5B, 0x60),
    (0x7B, 0x7E),
]

# `clean_text` keeps tabs and line breaks as ordinary whitespace.
CONTROL_WHITESPACE_EXCEPTIONS = {0x09, 0x0A, 0x0D}

# `clean_text` also drops the replacement character, which is not a control.
EXTRA_CONTROL = {0xFFFD}


def code_points():
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


def is_control(cp):
    if cp in EXTRA_CONTROL:
        return True
    if cp in CONTROL_WHITESPACE_EXCEPTIONS:
        return False
    return unicodedata.category(chr(cp)) in ("Cc", "Cf", "Co")


def is_space(cp):
    return chr(cp).isspace()


def is_chinese(cp):
    return any(first <= cp <= last for first, last in CHINESE_RANGES)


def is_punctuation(cp):
    if any(first <= cp <= last for first, last in ASCII_PUNCTUATION_RANGES):
        return True
    return unicodedata.category(chr(cp)).startswith("P")


def fold(cp):
    """Lowercase, then canonical decomposition without nonspacing marks."""
    lowered = chr(cp).lower()
    decomposed = unicodedata.normalize("NFD", lowered)
    return "".join(ch for ch in decomposed if unicodedata.category(ch) != "Mn")


def to_ranges(predicate):
    ranges = []
    for cp in code_points():
        if not predicate(cp):
            continue
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def collect_folds():
    entries = []
    skipped = 0
    for cp in code_points():
        if HANGUL_SBASE <= cp < HANGUL_SBASE + HANGUL_SCOUNT:
            skipped += 1
            continue
        if is_control(cp) or is_space(cp) or is_chinese(cp):
            continue
        expansion = fold(cp)
        if expansion == chr(cp):
            continue
        entries.append((cp, expansion))
    return entries, skipped

def emit():
    tables = {
        "Control": to_ranges(is_control),
        "Space": to_ranges(is_space),
        "Chinese": to_ranges(is_chinese),
        "Punctuation": to_ranges(is_punctuation),
    }
    folds, hangul_skipped = collect_folds()

    blob = bytearray()
    entries = []
    for cp, expansion in folds:
        encoded = expansion.encode("utf-8")
        offset = len(blob)
        blob.extend(encoded)
        entries.append((cp, offset, len(encoded)))

    lines = []
    lines.append("/* Generated by tools/gen_unicode_tables.py. Do not edit by hand. */")
    lines.append("")
    lines.append('#include "fsv_unicode_tables.h"')
    lines.append("")
    lines.append("namespace fsv {")
    lines.append("namespace uni {")
    lines.append("namespace detail {")
    lines.append("")
    for name, ranges in tables.items():
        lines.append("const Range k%sRanges[] = {" % name)
        for first, last in ranges:
            lines.append("    {0x%X, 0x%X}," % (first, last))
        lines.append("};")
        lines.append("const unsigned k%sRangeCount = %d;" % (name, len(ranges)))
        lines.append("")
    lines.append("const FoldEntry kFoldEntries[] = {")
    for cp, offset, length in entries:
        lines.append("    {0x%X, %d, %d}," % (cp, offset, length))
    lines.append("};")
    lines.append("const unsigned kFoldEntryCount = %d;" % len(entries))
    lines.append("")
    lines.append("const char kFoldBlob[] =")
    raw = bytes(blob)
    for start in range(0, len(raw), 24):
        piece = raw[start:start + 24]
        lines.append("    " + " ".join('"%s"' % ("\\x%02x" % b) for b in piece))
    if not raw:
        lines.append('    ""')
    lines.append("    ;")
    lines.append("const unsigned kFoldBlobSize = %d;" % len(raw))
    lines.append("")
    lines.append("}  // namespace detail")
    lines.append("}  // namespace uni")
    lines.append("}  // namespace fsv")
    lines.append("")
    with open(OUT_CPP, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))

    header = [0]
    header[0] = "/* Generated by tools/gen_unicode_tables.py. Do not edit by hand. */"
    body = [
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace fsv {",
        "namespace uni {",
        "namespace detail {",
        "",
        "struct Range {",
        "    uint32_t first;",
        "    uint32_t last;",
        "};",
        "",
        "struct FoldEntry {",
        "    uint32_t code_point;",
        "    uint32_t offset;",
        "    uint32_t length;",
        "};",
        "",
        "extern const Range kControlRanges[];",
        "extern const unsigned kControlRangeCount;",
        "extern const Range kSpaceRanges[];",
        "extern const unsigned kSpaceRangeCount;",
        "extern const Range kChineseRanges[];",
        "extern const unsigned kChineseRangeCount;",
        "extern const Range kPunctuationRanges[];",
        "extern const unsigned kPunctuationRangeCount;",
        "extern const FoldEntry kFoldEntries[];",
        "extern const unsigned kFoldEntryCount;",
        "extern const char kFoldBlob[];",
        "extern const unsigned kFoldBlobSize;",
        "",
        "}  // namespace detail",
        "}  // namespace uni",
        "}  // namespace fsv",
        "",
    ]
    with open(OUT_H, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header[0] + "\n" + "\n".join(body))

    print("control ranges     :", len(tables["Control"]))
    print("space ranges       :", len(tables["Space"]))
    print("chinese ranges     :", len(tables["Chinese"]))
    print("punctuation ranges :", len(tables["Punctuation"]))
    print("fold entries       :", len(entries), "(%d bytes of expansions)" % len(raw))
    print("hangul syllables   :", hangul_skipped, "expanded in code")


if __name__ == "__main__":
    emit()