"""Playback backend contract used by the music service."""

from __future__ import annotations

from typing import Protocol


class MusicPlaybackBackend(Protocol):
    @property
    def is_logged_in(self) -> bool: ...

    @property
    def is_playing(self) -> bool: ...

    @property
    def is_paused(self) -> bool: ...

    @property
    def play_mode(self) -> str: ...

    @property
    def volume(self) -> float: ...

    @property
    def queue(self) -> list: ...

    @property
    def current_index(self) -> int: ...

    def refresh_login_status(self) -> None: ...
    def clear_user_data(self) -> dict[str, int]: ...
    def cleanup(self) -> None: ...
    def move_queue_item(self, index: int, direction: int) -> int: ...
    def remove_queue_item(self, index: int) -> bool: ...
    def remove_song_from_history(self, song_id) -> bool: ...
    def next_track(self) -> None: ...
    def remove_current_queue_item(self) -> bool: ...
    def clear_queue(self) -> None: ...
    def pause(self) -> None: ...
