/* Generated by tools/gen_unicode_tables.py. Do not edit by hand. */

#pragma once

#include <cstdint>

namespace fsv {
namespace uni {
namespace detail {

struct Range {
    uint32_t first;
    uint32_t last;
};

struct FoldEntry {
    uint32_t code_point;
    uint32_t offset;
    uint32_t length;
};

extern const Range kControlRanges[];
extern const unsigned kControlRangeCount;
extern const Range kSpaceRanges[];
extern const unsigned kSpaceRangeCount;
extern const Range kChineseRanges[];
extern const unsigned kChineseRangeCount;
extern const Range kPunctuationRanges[];
extern const unsigned kPunctuationRangeCount;
extern const FoldEntry kFoldEntries[];
extern const unsigned kFoldEntryCount;
extern const char kFoldBlob[];
extern const unsigned kFoldBlobSize;

}  // namespace detail
}  // namespace uni
}  // namespace fsv
